[default]
check-file = true
check-filename = true
locale = "en-us"

[files]
extend-exclude = [
  ".build",
  ".cache",
  ".godot",
  ".gradle",
  ".kotlin",
  ".lua_modules",
  ".zig-cache",
  "_build",
  "build",
  "bun.lock",
  "coverage",
  "Dagger/dagger/src/index.ts",
  "deps",
  "dist",
  "dist-newstyle",
  "node_modules",
  "out",
  "sbom",
  "target",
  "testers/*/dagger/src/index.ts",
  "vendor",
  "zig-out",
  "zig-pkg",
]
