set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(TOOLCHAIN_TRIPLET "x86_64-w64-mingw32")

set(CMAKE_C_COMPILER "${TOOLCHAIN_TRIPLET}-gcc")
set(CMAKE_RC_COMPILER "${TOOLCHAIN_TRIPLET}-windres")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
