name = "project_name"
version = "0.1.0"
description = "A strict modern Fortran project."
license = "MIT OR Apache-2.0"
author = ["Project Maintainers"]
maintainer = ["maintainers@example.com"]
copyright = "Copyright 2026 Project Maintainers"
categories = ["library"]
keywords = ["fortran"]

[build]
auto-executables = false
auto-examples = false
auto-tests = false

[fortran]
implicit-external = false
implicit-typing = false
source-form = "free"

[library]
source-dir = "src"

[[executable]]
name = "project-name"
main = "main.f90"
source-dir = "app"

[[test]]
name = "project-tests"
main = "main.f90"
source-dir = "test"

[install]
library = true

[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
test-drive.tag = "v0.6.1"

[extra.ford]
author = "Project Maintainers"
display = ["public", "protected"]
graph = false
output_dir = "build/doc"
preprocess = false
project = "project_name"
search = true
source = true
src_dir = ["src"]
summary = "Strict modern Fortran project template."
