include_fragments = "anchor-only"
include_verbatim = false
no_progress = true

exclude_path = [
  "(^|/)\\.next/",
  "(^|/)\\.nuxt/",
  "(^|/)\\.svelte-kit/",
  "(^|/)\\.turbo/",
  "(^|/)\\.vite/",
  "(^|/)build/",
  "(^|/)coverage/",
  "(^|/)dist/",
  "(^|/)node_modules/",
  "(^|/)out/",
  "(^|/)sbom/",
]
