version: "2"

run:
  timeout: 3m
  tests: true

linters:
  default: none
  enable:
    - bidichk
    - copyloopvar
    - errcheck
    - errorlint
    - gosec
    - govet
    - ineffassign
    - nilerr
    - nilnil
    - revive
    - staticcheck
    - unused
  settings:
    revive:
      severity: error
      rules:
        - name: context-as-argument
        - name: error-return
        - name: error-strings
        - name: receiver-naming
        - name: var-naming

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
