package standards_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestFormattingPreservesGeneratedAndVendoredFiles(t *testing.T) {
	t.Parallel()

	project := t.TempDir()
	tasks, err := os.ReadFile(filepath.Join("..", ".config", "mise", "conf.d", "20-go.toml"))
	if err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(project, "mise.toml"), string(tasks))
	lock, err := os.ReadFile(filepath.Join("..", ".config", "mise", "mise.lock"))
	if err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(project, "mise.lock"), string(lock))
	const clean = "package sample\n\nvar Value = 1\n"
	const unformatted = "package sample\n\nvar Value=1\n"
	files := map[string]string{
		"source.go":                clean,
		"generated.go":             "// Code generated by fixture. DO NOT EDIT.\n\npackage sample\n\nvar (\n\tValue = 1\n)\n",
		"testdata/input.go":        unformatted,
		"vendor/dependency/lib.go": unformatted,
	}
	for name, source := range files {
		writeFile(t, filepath.Join(project, name), source)
	}

	runTask(t, project, "go:fmt:check", true)
	writeFile(t, filepath.Join(project, "source.go"), unformatted)
	runTask(t, project, "go:fmt:check", false)
	runTask(t, project, "go:fmt", true)
	runTask(t, project, "go:fmt:check", true)

	for name, expected := range files {
		actual, readErr := os.ReadFile(filepath.Join(project, name)) // #nosec G304 -- Names come from the fixed fixture map under t.TempDir.
		if readErr != nil {
			t.Fatal(readErr)
		}
		if string(actual) != expected {
			t.Errorf("%s: formatting changed an excluded file or failed to format source", name)
		}
	}
}

func writeFile(t *testing.T, name, contents string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(name), 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(name, []byte(contents), 0o600); err != nil { // #nosec G703 -- Callers supply only fixed fixture paths under t.TempDir.
		t.Fatal(err)
	}
}

func runTask(t *testing.T, project, task string, wantSuccess bool) {
	t.Helper()
	command := exec.CommandContext(t.Context(), "mise", "-C", project, "run", task) // #nosec G204 -- Fixed test cases select known tasks without a shell.
	command.Env = append(os.Environ(), "MISE_TRUSTED_CONFIG_PATHS="+project, "MISE_LOCKED=1")
	output, err := command.CombinedOutput()
	if (err == nil) != wantSuccess {
		t.Fatalf("%s: expected success=%t, got %v\n%s", task, wantSuccess, err, output)
	}
	if !wantSuccess && !strings.Contains(string(output), "source.go") {
		t.Fatalf("%s failed without identifying source.go:\n%s", task, output)
	}
}
