set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(TOOLCHAIN_TRIPLET "x86_64-w64-mingw32")

set(CMAKE_C_COMPILER "${TOOLCHAIN_TRIPLET}-gcc")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_TRIPLET}-g++")
set(CMAKE_RC_COMPILER "${TOOLCHAIN_TRIPLET}-windres")

set(CMAKE_FIND_ROOT_PATH "/usr/${TOOLCHAIN_TRIPLET}")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
